name: safeimagekit
title: Website Tools
email: Website-Tools@example.com
description: Simple to use online alarm clock to wake up after specific time or at specific times
baseurl: "" # the subpath of your site, e.g. /blog
url: https://safeimagekit.com # the base hostname & protocol for your site, e.g. http://example.com
siteurl: https://safeimagekit.com
twitter_username: jekyllrb
github_username: jekyll
favicon: /picture.png
logo: /picture.png
paginate: "12"
paginate_path: "/blog/page:num/"
alternateName: safeimagekit
theme: appscms-tools-theme
disqus:
  shortname: utils
# Build settings
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

production_google_analytics: "UA-179965937-20"
development_google_analytics: ""
