[[redirects]]
  from = "/placeholder-images/sitemap.xml"
  to = "https://placeholderimages.netlify.app/sitemap.xml"
  force = true
  status = 200

[[redirects]]
  from = "/placeholder-image-generator-tools"
  to = "https://placeholderimages.netlify.app/placeholder-image-generator-tools"
  force = true
  status = 200	

[[redirects]]
  from = "/placeholder-images"
  to = "https://placeholderimages.netlify.app/placeholder-images"
  force = true
  status = 200

[[redirects]]
  from = "/placeholder-images*"
  to = "https://placeholderimages.netlify.app/placeholder-images/:splat"
  force = true
  status = 200
  
  
[[redirects]]
  from = "/conv/sitemap.xml"
  to = "https://safeimagekitconv.netlify.app/sitemap.xml"
  force = true
  status = 200

[[redirects]]
  from = "/conv"
  to = "https://safeimagekitconv.netlify.app"
  force = true
  status = 200

[[redirects]]
  from = "/conv*"
  to = "https://safeimagekitconv.netlify.app/conv/:splat"
  force = true
  status = 200
  
  [[redirects]]
  from = "/facebook/sitemap.xml"
  to = "https://imagekit-facebook.netlify.app/sitemap.xml"
  force = true
  status = 200

[[redirects]]
  from = "/facebook*"
  to = "https://imagekit-facebook.netlify.app/facebook/:splat"
  force = true
  status = 200
